create table public.user_book_progress (
  id bigint generated by default as identity primary key,
  user_id integer not null,
  book_id text not null,
  last_learned_word_id bigint null,
  learned_count integer not null default 0,
  is_completed boolean not null default false,
  started_at timestamptz not null default now(),
  last_studied_at timestamptz not null default now(),
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_book_progress_user_book_unique unique (user_id, book_id),
  constraint user_book_progress_learned_count_check check (learned_count >= 0),
  constraint user_book_progress_completion_check check (
    (is_completed and completed_at is not null)
    or (not is_completed and completed_at is null)
  ),
  constraint user_book_progress_user_fkey
    foreign key (user_id) references public."User"(id)
    on update restrict on delete restrict,
  constraint user_book_progress_book_fkey
    foreign key (book_id) references public.books(book_id)
    on update restrict on delete restrict,
  constraint user_book_progress_last_word_fkey
    foreign key (last_learned_word_id) references public.words(id)
    on update restrict on delete restrict
);

create index user_book_progress_user_recent_idx
  on public.user_book_progress (user_id, last_studied_at desc);

create index user_book_progress_book_idx
  on public.user_book_progress (book_id);
