create table public.user_word_progress (
  id bigint generated by default as identity primary key,
  user_id integer not null,
  book_id text not null,
  word_id bigint not null,
  learned_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_word_progress_unique unique (user_id, book_id, word_id),
  constraint user_word_progress_user_fkey
    foreign key (user_id) references public."User"(id)
    on update restrict on delete restrict,
  constraint user_word_progress_book_fkey
    foreign key (book_id) references public.books(book_id)
    on update restrict on delete restrict,
  constraint user_word_progress_word_fkey
    foreign key (word_id) references public.words(id)
    on update restrict on delete restrict
);

create index user_word_progress_user_book_idx
  on public.user_word_progress (user_id, book_id);

